version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: master
  reviewers: []
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: master
  reviewers: []
  labels:
  - gh-actions
  - dependencies
  commit-message:
    prefix: ci
    include: scope