name: Build & Push to Docker Image Registry (Docker Hub & GitHub Container Registry)

on:
  release:
    types: [created]
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/docker.yaml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: hazmi35
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.14.1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tags
        run: echo ::set-output name=name::${GITHUB_REF##*/}

      - name: Generate Docker image metadata
        uses: docker/metadata-action@v5.5.0
        id: img_meta
        with:
          flavor: |
            latest=auto
          images: |
            hazmi35/pak-ustadz
            ghcr.io/Hazmi35/pak-ustadz
          tags: |
            ${{ steps.tags.outputs.name }}
            latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./
          platforms: linux/amd64
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Update repo description
        continue-on-error: true
        if: ${{ github.event_name == 'release' }}
        uses: peter-evans/dockerhub-description@v3.0.0
        with:
         username: hazmi35
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         repository: hazmi35/pak-ustadz