name: Build & Push to Docker Image Registry (Docker Hub & GitHub Container Registry)

on:
  release:
    types: [created]
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/docker.yaml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: hazmi35
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker image metadata
        uses: docker/metadata-action@v5.5.1
        id: img_meta
        with:
          flavor: |
            latest=auto
          images: |
            docker.io/${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha,prefix=,suffix=,format=short

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Update Docker repo description
        if: ${{ github.event_name == 'release' }}
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
         username: hazmi35
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         repository: hazmi35/pak-ustadz
