name: Lint & Compile test code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  lint-compile:
    uses: Hazmi35/workflows/.github/workflows/pnpm-eslint-typescript.yaml@master
    secrets: inherit
